# SPDX-FileCopyrightText: 2024 BratishkaErik and zigtut.org contributors
#
# SPDX-License-Identifier: CC0-1.0

version = 1

[[annotations]]
path = "src/content/docs/**/*.zig"
# Licensing and copyright info in file header, if any, has precedence over this.
# This is a fallback for files that do not have this header.
precedence = "closest"
SPDX-FileCopyrightText = [
	"2020 Sobeston and zig.guide contributors",
	"2024 BratishkaErik and zigtut.org contributors",
]

SPDX-License-Identifier = "MIT"
