# SPDX-FileCopyrightText: 2024 BratishkaErik and zigtutor.ru contributors
#
# SPDX-License-Identifier: CC0-1.0

version = 1

[[annotations]]
path = "src/content/docs/**/*.zig"
precedence = "override"
SPDX-FileCopyrightText = [
	"2020 Sobeston and zig.guide contributors",
	"2024 BratishkaErik and zigtutor.ru contributors",
]

SPDX-License-Identifier = "MIT"
